version: '3.7'

services:
  
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    restart: on-failure
    environment:
      - SA_PASSWORD=QWEqwe123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ${REPOSITORCH_HOME_PATH}/mssql:/var/opt/mssql
