version: '3.7'

services:
  
  repositorch:
    build:
      context: ./
      dockerfile: ../src/Repositorch.Web/Dockerfile
    restart: on-failure
    ports:
      - "5000:80"
    environment:
      - REPOSITORCH_HOME_PATH=/root/data
      - REPOSITORCH_REPO_PATH=/root/repo
    volumes:
      - ${REPOSITORCH_HOME_PATH}:/root/data
      - ${REPOSITORCH_REPO_PATH}:/root/repo
      