version: '3.7'

services:
  
  repositorch:
    build:
      context: ../src
      dockerfile: ./Repositorch.Web/Dockerfile
    env_file: ../docker/.env
    container_name: repositorch
    restart: on-failure
    ports:
      - "5000:80"
    environment:
      - REPOSITORCH_HOME_PATH=/root/data
      - REPOSITORCH_REPO_PATH=/root/repo
    volumes:
      - ${REPOSITORCH_HOME_PATH}:/root/data
      - ${REPOSITORCH_REPO_PATH}:/root/repo
      