version: '3.8'

services:
  
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    deploy:
      restart_policy:
        condition: none
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=QWEqwe123
      - MSSQL_COLLATION=SQL_Latin1_General_CP1_CS_AS
    ports:
      - 1433:1433
    volumes:
      - ${REPOSITORCH_HOME_PATH}/mssql:/var/opt/mssql/data
