version: '3.7'

services:
      
  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    user: root
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ${REPOSITORCH_HOME_PATH}/postgresql:/var/lib/postgresql
